packages:
  - apps/*
  - apps/*/*
  - apps/*/deploy/*
  - apps/*/deploy/aws/sdks/neon
  - packages/typescript/*
allowBuilds:
  '@parcel/watcher': true
  '@pulumi/command': true
  '@pulumi/neon': true
  esbuild: true
  less: true
  lmdb: false
  msgpackr-extract: false
  nx: false
  protobufjs: true
