#!/usr/bin/env node
/**
 * Syncs @atta/product SemVer into sibling package.json files and regenerates
 * Go/TS build identity. Source of truth for SemVer: apps/atta/package.json.
 *
 * Build number (monotonic int, store-safe):
 *   1. ATTA_BUILD env if set (CI should set this, e.g. GITHUB_RUN_NUMBER)
 *   2. else git rev-list --count HEAD
 *
 * Revision (VCS identity, not for store ordering):
 *   1. ATTA_REVISION or GITHUB_SHA (shortened to 7)
 *   2. else git rev-parse --short=7 HEAD
 *
 * Release datetime (ISO 8601, includes time):
 *   1. ATTA_RELEASED_AT env if set
 *   2. else git log -1 --format=%cI
 *
 * App channel (APP_ENV → local|staging|production):
 *   1. APP_ENV if set (exact values only; no aliases)
 *   2. else local (local sync convenience only)
 *
 * Usage:
 *   node apps/atta/scripts/sync-version.mjs          # write
 *   node apps/atta/scripts/sync-version.mjs --check  # SemVer drift only
 */
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ANDROID_VERSION_CODE_MAX = 2_100_000_000;
const checkOnly = process.argv.includes('--check');
const productRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(productRoot, '../..');
const productPkg = JSON.parse(readFileSync(join(productRoot, 'package.json'), 'utf8'));
const version = productPkg.version;

if (typeof version !== 'string' || !/^\d+\.\d+\.\d+(-[\w.-]+)?$/.test(version)) {
  console.error(`invalid @atta/product version: ${JSON.stringify(version)}`);
  process.exit(1);
}

function git(args) {
  return execSync(`git ${args}`, { cwd: repoRoot, encoding: 'utf8' }).trim();
}

function resolveBuild() {
  const fromEnv = process.env.ATTA_BUILD?.trim();
  if (fromEnv) {
    if (!/^\d+$/.test(fromEnv)) {
      console.error(`ATTA_BUILD must be a positive integer, got ${JSON.stringify(fromEnv)}`);
      process.exit(1);
    }
    const n = Number(fromEnv);
    if (n < 1 || n > ANDROID_VERSION_CODE_MAX) {
      console.error(`ATTA_BUILD out of range 1..${ANDROID_VERSION_CODE_MAX}: ${n}`);
      process.exit(1);
    }
    return n;
  }
  try {
    const count = Number(git('rev-list --count HEAD'));
    if (!Number.isInteger(count) || count < 1) {
      throw new Error(`unexpected rev-list count: ${count}`);
    }
    if (count > ANDROID_VERSION_CODE_MAX) {
      console.error(`git rev-list count ${count} exceeds Android versionCode max`);
      process.exit(1);
    }
    return count;
  } catch (err) {
    console.error('cannot resolve build number (set ATTA_BUILD or use a full git clone)');
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  }
}

function resolveRevision() {
  const fromEnv = (process.env.ATTA_REVISION ?? process.env.GITHUB_SHA)?.trim();
  if (fromEnv) {
    return fromEnv.replace(/^g/, '').slice(0, 7);
  }
  try {
    return git('rev-parse --short=7 HEAD');
  } catch {
    return 'unknown';
  }
}

function resolveReleasedAt() {
  const isoPrefix = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/;
  const fromEnv = process.env.ATTA_RELEASED_AT?.trim();
  if (fromEnv) {
    if (!isoPrefix.test(fromEnv)) {
      console.error(`ATTA_RELEASED_AT must be ISO 8601 datetime, got ${JSON.stringify(fromEnv)}`);
      process.exit(1);
    }
    return fromEnv;
  }
  try {
    const date = git('log -1 --format=%cI');
    if (!isoPrefix.test(date)) {
      throw new Error(`unexpected git datetime: ${date}`);
    }
    return date;
  } catch (err) {
    console.error('cannot resolve release datetime (set ATTA_RELEASED_AT or use a git checkout)');
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  }
}

function resolveAppEnv() {
  const raw = (process.env.APP_ENV || '').trim().toLowerCase();
  switch (raw) {
    case 'local':
    case '':
      return 'local';
    case 'staging':
      return 'staging';
    case 'production':
      return 'production';
    default:
      console.error(`APP_ENV must be local|staging|production, got ${JSON.stringify(raw)}`);
      process.exit(1);
  }
}

const build = resolveBuild();
const revision = resolveRevision();
const releasedAt = resolveReleasedAt();
const appEnv = resolveAppEnv();

const childPackageRels = [
  'backend/package.json',
  'pwa/package.json',
  'e2e/package.json',
  'deploy/aws/package.json',
  'deploy/onprem/package.json',
];

const goPath = join(productRoot, 'backend/internal/platform/product/version.go');
const goExpected = `// Code generated by apps/atta/scripts/sync-version.mjs; DO NOT EDIT.

package product

// Name is the internal habitat codename. Never show it in user-facing UI.
const Name = "Atta"

const (
\tVersion    = "${version}"
\tBuild      = ${build}
\tRevision   = "${revision}"
\tReleasedAt = "${releasedAt}"
\tAppEnv     = "${appEnv}"
)
`;

const tsBuildPath = join(productRoot, 'src/build-info.ts');
const tsBuildExpected = `// Code generated by apps/atta/scripts/sync-version.mjs; DO NOT EDIT.

/** Monotonic build number (Android versionCode / CFBundleVersion / package revision). */
export const PRODUCT_BUILD = ${build};

/** Short VCS revision for support; not used for store ordering. */
export const PRODUCT_REVISION = '${revision}';

/** Release datetime (ISO 8601) for this build identity. */
export const PRODUCT_RELEASED_AT = '${releasedAt}';

/** Deployment channel baked at build time: local | staging | production. */
export const APP_ENV = '${appEnv}' as const;
`;

let drifted = false;

for (const rel of childPackageRels) {
  const path = join(productRoot, rel);
  const child = JSON.parse(readFileSync(path, 'utf8'));
  if (child.version === version) {
    continue;
  }
  drifted = true;
  if (checkOnly) {
    console.error(`${rel}: version ${child.version} != product ${version}`);
    continue;
  }
  child.version = version;
  writeFileSync(path, `${JSON.stringify(child, null, 2)}\n`);
  console.log(`updated ${rel} -> ${version}`);
}

function readOrEmpty(path) {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

const goCurrent = readOrEmpty(goPath);
const versionMatch = goCurrent.match(/Version\s*=\s*"([^"]+)"/);
if (!versionMatch || versionMatch[1] !== version) {
  drifted = true;
  if (checkOnly) {
    console.error(`backend/internal/platform/product/version.go SemVer out of sync (want ${version})`);
  }
}

if (checkOnly && drifted) {
  console.error('run: pnpm --filter @atta/product sync-version');
  process.exit(1);
}

if (checkOnly) {
  process.exit(0);
}

mkdirSync(dirname(goPath), { recursive: true });
if (goCurrent !== goExpected) {
  writeFileSync(goPath, goExpected);
  console.log(`updated backend/internal/platform/product/version.go -> ${version}+${build} (${revision}) ${releasedAt} [${appEnv}]`);
}

mkdirSync(dirname(tsBuildPath), { recursive: true });
if (readOrEmpty(tsBuildPath) !== tsBuildExpected) {
  writeFileSync(tsBuildPath, tsBuildExpected);
  console.log(`updated src/build-info.ts -> build ${build} (${revision}) ${releasedAt} [${appEnv}]`);
}

console.log(`synced product ${version} build ${build} revision ${revision} released ${releasedAt} env ${appEnv}`);
