// Code generated by apps/atta/scripts/sync-version.mjs; DO NOT EDIT.

package product

// Name is the internal habitat codename. Never show it in user-facing UI.
const Name = "Atta"

const (
	Version    = "0.1.0"
	Build      = 477
	Revision   = "01f97ba"
	ReleasedAt = "2026-09-18T17:34:14-05:00"
	AppEnv     = "local"
)
