/** IAM inline policy documents for Identity Center permission sets. */

/**
 * Deny secrets exposure and high-impact mutations for AI MCP / agentic debug.
 * Attach alongside ReadOnlyAccess on the ProductMCP permission set.
 */
export const productMcpDenyPolicy = {
  Version: '2012-10-17',
  Statement: [
    {
      Sid: 'DenySecretsAndCredentialReads',
      Effect: 'Deny',
      Action: [
        'secretsmanager:GetSecretValue',
        'secretsmanager:BatchGetSecretValue',
        'ssm:GetParameter',
        'ssm:GetParameters',
        'ssm:GetParameterHistory',
        'ssm:GetParametersByPath',
        'ssm:StartSession',
        'ssm:ResumeSession',
        'ec2:GetPasswordData',
        'lambda:GetFunction',
        'lambda:GetFunctionConfiguration',
        'ecs:DescribeTaskDefinition',
        'cloudformation:GetTemplate',
      ],
      Resource: '*',
    },
    {
      Sid: 'DenyDestructiveAndMutatingOps',
      Effect: 'Deny',
      Action: [
        'cloudformation:CreateStack',
        'cloudformation:UpdateStack',
        'cloudformation:DeleteStack',
        'cloudformation:ExecuteChangeSet',
        'cloudtrail:StopLogging',
        'cloudtrail:DeleteTrail',
        'cloudtrail:UpdateTrail',
        'dynamodb:DeleteTable',
        'ec2:TerminateInstances',
        'ec2:StopInstances',
        'ec2:CreateNatGateway',
        'ec2:CreateTransitGateway',
        'ecr:DeleteRepository',
        'ecs:DeleteService',
        'ecs:DeleteCluster',
        'eks:DeleteCluster',
        'elasticloadbalancing:DeleteLoadBalancer',
        'guardduty:DeleteDetector',
        'iam:*',
        'kms:ScheduleKeyDeletion',
        'kms:DisableKey',
        'kms:PutKeyPolicy',
        'lambda:DeleteFunction',
        'lambda:UpdateFunctionCode',
        'lambda:UpdateFunctionConfiguration',
        'organizations:*',
        'rds:DeleteDBInstance',
        'rds:DeleteDBCluster',
        'rds:DeleteDBSnapshot',
        'rds:DeleteDBClusterSnapshot',
        's3:DeleteBucket',
        's3:DeleteObject',
        's3:DeleteObjectVersion',
        's3:PutBucketPolicy',
        's3:DeleteBucketPolicy',
        'sso:*',
        'sso-directory:*',
      ],
      Resource: '*',
    },
  ],
} as const;
