// Code generated by apps/atta/scripts/sync-version.mjs; DO NOT EDIT.

/** Monotonic build number (Android versionCode / CFBundleVersion / package revision). */
export const PRODUCT_BUILD = 477;

/** Short VCS revision for support; not used for store ordering. */
export const PRODUCT_REVISION = '01f97ba';

/** Release datetime (ISO 8601) for this build identity. */
export const PRODUCT_RELEASED_AT = '2026-09-18T17:34:14-05:00';

/** Deployment channel baked at build time: local | staging | production. */
export const APP_ENV = 'local' as const;
